<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Element_1630056240099</name>
   <tag></tag>
   <elementGuidId>6256ec67-fd2f-470b-9a71-02c02b8a2b5c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='InvoiceImage']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;InvoiceImage&quot;][count(. | //*[@id = 'InvoiceImage']) = count(//*[@id = 'InvoiceImage'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;InvoiceImage&quot;]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>InvoiceImage</value>
   </webElementProperties>
</WebElementEntity>
