<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_PO_fa fa-share-square-o maven-icon selfAssign</name>
   <tag></tag>
   <elementGuidId>e3d43c90-c2ae-4140-8118-96e363c06778</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='auditListTable']/tbody/tr/td[9]/ul/li/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.fa.fa-share-square-o.maven-icon.selfAssign</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-share-square-o maven-icon selfAssign</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;ng-scope&quot;]/body[@class=&quot;ng-scope block-ui block-ui-anim-fade&quot;]/ui-view[@class=&quot;ng-scope&quot;]/grn-component[@class=&quot;ng-scope ng-isolate-scope&quot;]/div[@class=&quot;gl-manage-container row&quot;]/div[@class=&quot;gl-manage-action-panel col-sm-12&quot;]/div[@class=&quot;col-sm-12 col-md-12&quot;]/div[@class=&quot;tab-content&quot;]/div[@class=&quot;main-list&quot;]/div[@id=&quot;grnListPagination&quot;]/table[@id=&quot;auditListTable&quot;]/tbody[@class=&quot;ng-scope&quot;]/tr[1]/td[@class=&quot;gl-table-list-data text-center ellipsisTd&quot;]/ul[@class=&quot;action-box conflict&quot;]/li[@class=&quot;ng-scope&quot;]/i[@class=&quot;fa fa-share-square-o maven-icon selfAssign&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='auditListTable']/tbody/tr/td[9]/ul/li/i</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/i</value>
   </webElementXpaths>
</WebElementEntity>
